name: TikTok Auto Download

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test scheduler
        run: echo "Scheduled run working at $(date)"